// <auto-generated />
using System;
using API_Feedback.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Feedback.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250618150356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Feedback.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remetente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TB_FEEDBACKS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(2025, 4, 10, 8, 5, 20, 0, DateTimeKind.Unspecified),
                            Descricao = "O ventilador da sala 7 foi concertado com sucesso. Favor dar baixa no chamado pelo sistema.",
                            Destinatario = "Daniela",
                            Remetente = "Kelly"
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(2025, 4, 15, 12, 50, 31, 0, DateTimeKind.Unspecified),
                            Descricao = "A visita do técnico precisou ser adiada, peço que aguarde mais alguns dias até a resolução do problema no pc do lab 4.",
                            Destinatario = "Lucas",
                            Remetente = "Marion"
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(2025, 4, 18, 7, 15, 44, 0, DateTimeKind.Unspecified),
                            Descricao = "A tela do pc do lab 4 foi trocada com sucesso, agradeço a paciencia. Favor dar baixa no chamado pelo sistema.",
                            Destinatario = "Lucas",
                            Remetente = "Marion"
                        },
                        new
                        {
                            Id = 4,
                            Data = new DateTime(2025, 4, 28, 17, 2, 28, 0, DateTimeKind.Unspecified),
                            Descricao = "Os mouses defeituosos do lab 2 foram substituídos com sucesso. Favor dar baixa no chamado pelo sistema.",
                            Destinatario = "Aline",
                            Remetente = "Luis"
                        },
                        new
                        {
                            Id = 5,
                            Data = new DateTime(2025, 5, 11, 13, 34, 12, 0, DateTimeKind.Unspecified),
                            Descricao = "Já encomendamos o vidro para a janela quebrada da sala 17 e o problema será resolvido o quanto antes.",
                            Destinatario = "Roberto",
                            Remetente = "Flávio"
                        },
                        new
                        {
                            Id = 6,
                            Data = new DateTime(2025, 5, 13, 9, 37, 53, 0, DateTimeKind.Unspecified),
                            Descricao = "A janela da sala 17 foi concertada com sucesso. Favor dar baixa no chamado pelo sistema.",
                            Destinatario = "Roberto",
                            Remetente = "Flávio"
                        },
                        new
                        {
                            Id = 7,
                            Data = new DateTime(2025, 5, 21, 14, 16, 49, 0, DateTimeKind.Unspecified),
                            Descricao = "O vazamento nos bebedouros do pátio foi resolvido imediatamente, agradecemos o aviso. Favor dar baixa no chamado pelo sistema.",
                            Destinatario = "Carlos",
                            Remetente = "Amanda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
